# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  json_path:
    description: "json_path"
    required: true
  package_name:
    description: "package_name"
    required: true
  hash_value:
    description: "hash_value"
    required: true
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.json_path }}
    - ${{ inputs.package_name }}
    - ${{ inputs.hash_value }}
