on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: pwd
        run: pwd

      - name: ls -la prev checkout
        run: ls -la

      - name: Checkout
        uses: actions/checkout@v3

      - name: ls -la after checkout
        run: ls -la

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          json_path: samples/sample.json
          package_name: "com.unity.package"
          hash_value: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
